[package]
name = "yacit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.24.1"
libc = "0.2.126"
socket2 = { version = "0.4.4", features = ["all"] }
